



# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = 'https://fetzner.me/'
title = "Alex Fetzner"
theme = 'hermit-v2'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true ## set to true to enable inbuilt robots.txt

#[languages]
#  [languages.en]
#    title = 'CHANGE ME'
#    [languages.en.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 1
#  [languages.fr]
#    title = 'CHANGE ME(FR)'
#    [languages.fr.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3

languageCode = "en-us"

# enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "MIT"
enableEmoji = true

#[services]
#  [services.disqus]
#    shortname = ''
#  [services.googleAnalytics]
#    id = ''

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "Alex Fetzner"
  about = "about-me/about-me"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
  description = "A portfolio website for IT professional Alex Fetzner"
  # images = [""]
  themeColor = "#494f5c"
  accentColor = "#018472"

  #homeSubtitle = "CHANGE ME HOME SUBTITLE"
  footerCopyright = ' <a href="https://opensource.org/licenses/MIT" target="_blank" rel="noopener">MIT License</a>'
  # footerHideThemeName = false
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = "10 minutes"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # listLayout = ["description","tags","categories","legacy"]
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  # mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  # mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
  [params.gallery]
    enable = true
    thumbnail = '300'

  [params.dateform]
    CopyrightDate = "2006"
    LongDate = "Jan 2, 2006"
    ShortDate = "Jan 2"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04 -0700"

  # [[params.socialLinks]]
  #   name = "mastodon"
  #   url = "https://joinmastodon.org/"
  #
  # [[params.socialLinks]]
  #   name = "x"
  #   url = "https://twitter.com/"

  # [[params.socialLinks]]
  #   name = "github"
  #   url = "https://github.com/Afetzner?tab=repositories"

[menu]

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 20

  [[menu.main]]
    name = "Resumés"
    url = "resumes/"
    weight = 30

